---
- hosts: all
  gather_facts: yes
  tasks: []

- hosts: consul_servers
  vars:
    consul_bootstrap_expect: 3
    consul_server_group_name: consul_servers
    consul_network_iface: enp0s8
    consul_node_name: "{{ inventory_hostname|to_uuid }}"
  roles:
    - ansible-consul

- hosts: consul_clients
  vars:
    consul_server_group_name: consul_servers
    consul_network_iface: enp0s8
    consul_node_name: "{{ inventory_hostname|to_uuid }}"
  roles:
    - ansible-consul
