---

# Check before creating log dir to prevent aggressively overwriting permissions
- name: Check consul log directory
  stat: path="{{ consul_log_file|dirname }}"
  register: consul_log_dir

- name: Create log directory
  file:
    path: "{{ consul_log_file|dirname }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  when: not consul_log_dir.stat.exists

- name: Touch the log file
  file:
    path: "{{ consul_log_file }}"
    state: touch
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"

- name: Create TLS key
  no_log: True
  copy:
    content: "{{ consul_tls_key }}"
    dest: "{{ consu_tls_key_file }}"
    owner: "{{ consul_owner }}"
    group: "{{ consul_group }}"
    mode: 0600
  when: consul_tls_key is defined
  notify:
    - restart consul

- name: Create TLS cert
  no_log: True
  copy:
    content: "{{ consul_tls_cert }}"
    dest: "{{ consul_tls_cert_file }}"
    owner: "{{ consul_owner }}"
    group: "{{ consul_group }}"
    mode: 0600
  when: consul_tls_cert is defined
  notify:
    - restart consul

- name: Create TLS root CA cert
  no_log: True
  copy:
    content: "{{ consul_tls_ca_cert }}"
    dest: "{{ consul_tls_ca_cert_file }}"
    owner: "{{ consul_owner }}"
    group: "{{ consul_group }}"
    mode: 0600
  when: consul_tls_ca_cert is defined
  notify:
    - restart consul

- name: Create config file
  template:
    src: consul.json.j2
    dest: "{{ consul_config_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644
  notify:
    - reload systemd

- name: Create Init Script
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart consul
