---
- name: Install Unzip
  apt:
    name: unzip
    update_cache: yes

- name: Create consul group
  group:
    name: "{{ consul_group }}"
    state: present
    system: yes

- name: Create consul user
  user:
    home: "{{ consul_home }}"
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    system: yes

- name: Create consul directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
    recurse: True
  with_items:
    - "{{ consul_home }}"
    - "{{ consul_home }}/bin"
    - "{{ consul_home }}/cert"
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"

- name: Download and unpack
  unarchive:
    src: "{{ consul_download_url }}"
    dest: "{{ consul_home }}/bin"
    remote_src: yes
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0700

- name: Add consul to PATH
  template:
    src: consul.sh.j2
    dest: /etc/profile.d/consul.sh
