---

- name: reload systemd
  become: True
  command: systemctl daemon-reload

- name: restart consul
  action: service name=consul state=restarted enabled=yes
  when: consul.restart_on_change|default(False) and consul_started.changed
